apiVersion: v1
kind: Service
metadata:
  name: movie-quote-service
  labels:
    app: movie-quote-app
    tier: backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: movie-quote-app
    tier: backend
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-login
data:
  rootPassword: UEAkJHcwcmQ=
  username: ZGJ1c2Vy
  password: ZGJwYXNz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-quote-service
  labels:
    app: movie-quote-app
    tier: backend
spec:
  selector:
    matchLabels:
      app: movie-quote-app
      tier: backend
  template:
    metadata:
      labels:
        app: movie-quote-app
        tier: backend
    spec:
      containers:
        - name: movie-quote-service
          image: g00glen00b/movie-quote-service:0.0.1
          imagePullPolicy: "Always"
          env:
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,metrics,prometheus"
            - name: MANAGEMENT_ENDPOINTS_HEALTH_SHOW-DETAILS
              value: "always"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://localhost:3600/quotes?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-login
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-login
                  key: password
            - name: SPRING_DATASOURCE_SCHEMA
              value: "classpath:schema-mysql.sql"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "always"
          ports:
            - containerPort: 8080
              name: service-port
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              port: service-port
              path: /actuator/health
            initialDelaySeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: service-port
              path: /actuator/health
            initialDelaySeconds: 10
            timeoutSeconds: 2
        - name: movie-quote-database
          image: mysql:8.0.14
          env:
            - name: MYSQL_ONETIME_PASSWORD
              value: true
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-login
                  key: rootPassword
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-login
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-login
                  key: password
            - name: MYSQL_DATABASE
              value: quotes

